<?php

// Remove some of the boxes from dashboard we don't need, make things less cluttered
function hale_remove_dashboard_metabox() {
    remove_meta_box('dashboard_primary', 'dashboard', 'side'); // WordPress News
    remove_meta_box('wpseo-dashboard-overview', 'dashboard', 'normal');
    remove_meta_box('dashboard_site_health', 'dashboard', 'normal');
}

add_action('admin_init', 'hale_remove_dashboard_metabox');

/**
 * Registers a custom dashboard widget in the WordPress admin dashboard.
 *
 * This function hooks into the 'wp_dashboard_setup' action to add a new widget
 * to the WordPress admin dashboard. The widget is titled "Support & Feature Requests"
 * and will display content generated by the `hale_custom_dashboard_widget_content` function.
 *
 * @return void
 */
function hale_add_dashboard_metabox_request_a_feature() {
    wp_add_dashboard_widget(
        'hale_add_dashboard_metabox_request_a_feature', // Widget slug
        'Website Builder support and feature requests',
        'hale_dashboard_metabox_request_a_feature_content'
    );
}
add_action('wp_dashboard_setup', 'hale_add_dashboard_metabox_request_a_feature');

function hale_dashboard_metabox_request_a_feature_content() {
    echo '<p>Submit a support request or request a new feature for your website:</p>';
    echo '<ul>
            <li><a href="https://forms.office.com/Pages/ResponsePage.aspx?id=KEeHxuZx_kGp4S6MNndq2J-bJGccQMhPj2sR7yqLpiJUMTRERTlXUldBT01RUERHTkoyMUw5UURRNC4u">Request a feature or report a bug form (external link)</a></li>
          </ul>';
}
